### PR TITLE
Fix to instantiate correct model depth

### PR DESCRIPTION
**Pull request by tayden**
Fixed incorrect range() calls that resulted in creating models of depth (N-1)\*6 + 4 instead of the correct N\*6 + 4 depth.

Fixes issue #12

### CODE REVIEW

**Comment by titu1994** [comment]
Have you run models.summary() to check that the number of parameters matches that of the paper for similar configs ?

**Comment by tayden** [comment]
Hmm, number of parameters look incorrect. The updates do give the expected depth and width values though and cause the range() loops to run N times, which I think is the desired behaviour.

**Comment by titu1994** [comment]
Not really. Matching the parameter count is important.

**Comment by tayden** [comment]
If that's the case then the bug is how the depth is being counted. See Issue #12

**Comment by tayden** [comment]
If you refer to the paper, you can see that each residual block (conv_2, conv_3, conv_4) should be stacked N times. The current code stacks N-1 blocks, which is wrong. 

Despite the incorrect number of parameters, I think this change is correct and that the incorrect number of parameters is due to some other bug.

**Comment by titu1994** [comment]
Expand conv is one of the conv blocks in the paper, which I separated out from the normal conv block call. That is why I have set N-1 blocks for the loops. 

The printed message may be the bug. However, the parameter count increasing is a sure sign that this commit is wrong in handling this issue.

**Pull request closed without merging**
